service:
  name: base
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  defaultRegion: us-east-1
  defaultEnvironmentGroup: dev
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, self:custom.defaultEnvironmentGroup}
  objectPrefix: '${self:service}-${self:custom.stage}'
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'      # Defaults to npm
    forceExclude:
      - "aws-sdk"

package:
  exclude:
    - aws-sdk
    - .aws-credentials

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  - ${file(./route/test-functions.yml)}