service:
  name: base-service


custom:
  apigwBinary:
    types:
    - "*/*"
  defaultRegion: us-east-1
  defaultEnvironmentGroup: dev
  region: ${opt:region, self:custom.defaultRegion}
  stage: ${opt:stage, env:USER}
  objectPrefix: '${self:service}-${self:custom.stage}'
  CNAME: media.artistscard.com
  S3NAME: artistscard-music.s3.amazonaws.com
  S3Identities: origin-access-identity/cloudfront/EIHHZWG2OBYET
  webpack:
    webpackConfig: ./webpack.config.js
    # includeModules: true
    includeModules:
      forceInclude:
        - class-transformer
        - class-validator
    packager: 'npm'      # Defaults to npm
    forceExclude:
      - "aws-sdk"
  imageServiceCustom:
    origin:
      DomainName: '${self:custom.S3NAME}'
      S3OriginConfig:
        OriginAccessIdentity: '${self:custom.S3Identities}'
    behavior:
      MaxTTL: 31536000
      MinTTL: 31536000
      DefaultTTL: 31536000
      Compress: true
      ViewerProtocolPolicy: allow-all
      ForwardedValues:
        Headers:
          - 'Origin'
          - 'Access-Control-Request-Method'
          - 'Access-Control-Request-Headers'
        QueryStringCacheKeys:
          - 'mode'
          - 'size'
          - 'format'
          - 'who'
          - 'timestamp'
          - 'error'
          - 'orininal'
          - 'fit'
        QueryString: true
      AllowedMethods:
        - 'GET'
        - 'HEAD'
        - 'OPTIONS'
        - 'PUT'
        - 'PATCH'
        - 'POST'
        - 'DELETE'
      CachedMethods:
        - 'GET'
        - 'HEAD'
        - 'OPTIONS'        


package:
  include:
    - private_key.pem
  exclude:
    - aws-sdk
    - .aws-credentials
    
# Add the serverless-webpack plugin
plugins:  
  - serverless-webpack
  - serverless-apigw-binary
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  endpointType: Edge  
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB    
    binaryMediaTypes:
      - '*/*'

# resources:
#   - ${file(./config/resources.yml)}

functions:
  - ${file(./route/test-functions.yml)}

  